### ISSUE TITLE
Missing community/contribution guidelines

### ISSUE THREAD

**Issue by klb2** [astro-informatics/sleplet#100]
This project is lacking guidelines for other people who wish to contribute, e.g,. through bug reports or pull requests.

The JOSS review checklist specifies this as
> **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

I think this should be clarified in a `CONTRIBUTING.md` file and Github issue templates should be added.

**Comment by paddyroddy** [comment]
Fixed in #122.
